# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Entity\QuestionCollection:
        arguments:
            - '@serializer'

    # Normalizers
    serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            $classMetadataFactory: null
            $nameConverter: null
            $propertyAccessor: '@property_accessor'
            $propertyTypeExtractor: null

    serializer.normalizer.array:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer

    serializer.normalizer.user_answer_collection:
        class: App\Serializer\UserAnswerCollectionNormalizer

    # Serializer configuration
    Symfony\Component\Serializer\Serializer:
        arguments:
            - ['@serializer.normalizer.user_answer_collection', '@serializer.normalizer.object', '@serializer.normalizer.array']
